name: Code Check with ESLint and Prettier
on:
  push:
    branches:
      - "*"

jobs:
  # lint:
  #   name: â¬£ ESLint
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   steps:
  #     - name: â¬‡ï¸ Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Set up bun
  #       uses: oven-sh/setup-bun@v1

  #     - name: â” Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18

  #     - name: ğŸ“¥ Download deps
  #       run: bun install

  #     - name: ğŸ”¬ Lint
  #       run: bun run lint

  prettier:
    name: ğŸ’… Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Download deps
        run: bun install

      - name: ğŸ’… Prettier check
        run: bun run format:check
